{% set version = "8.1.0" %}

package:
  name: av
  version: {{ version }}

source:
  fn: av-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/a/av/av-{{ version }}.tar.gz
  sha256: 0402169bc27e38e0f44e0e0e1854cf488337e86206b6d25d6dae2bfd7a1a0230

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    # 2022/02/06: hmaarrfk
    # Tests don't seem to be passing on azure with ppc64le
    - python setup.py test                   # [(build_platform == target_platform) and (not ppc64le)]
  run_exports:
    # PyAV now claims to follow semantic versioning
    - {{ pin_subpackage('av') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - pkg-config  # [not win]
  host:
    - python
    - pip
    - cython
    - numpy
    # pyav seems to depend on a symbol that may have
    # been removed in ffmpeg 4.4
    # https://github.com/conda-forge/ffmpeg-feedstock/pull/115#issuecomment-1019384624
    # Because of this, we pin the minor version in the run section as well
    # At the time of writing, pyav only tests with 4.3.2
    # https://github.com/PyAV-Org/PyAV/blob/main/scripts/fetch-vendor.json
    - ffmpeg 4.3
    - pillow
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pillow
    - ffmpeg 4.3

test:
  imports:
    - av
    - av.audio
    - av.audio.fifo

about:
  home: https://github.com/PyAV-Org/PyAV/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Pythonic bindings for FFmpeg.

  description: |
    PyAV is a Pythonic binding for FFmpeg or Libav. We aim to provide all of
    the power and control of the underlying library, but manage the gritty
    details as much as possible.
  doc_url: https://pyav.org/docs/develop/
  dev_url: https://github.com/PyAV-Org/PyAV/

extra:
  recipe-maintainers:
    - danielballan
    - mikeboers
    - sdvillal
    - h-vetinari
    - hmaarrfk
