{% set name = "av" %}
{% set version = "6.0.0" %}
{% set sha256 = "9037d73d7a812c3dc75d9cc27d03215483c9e782eae63a07142c0725c6bd2df0" %}
{% set build_number = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build_number }}
  skip: True  # [win and py27]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  run_exports:
    # PyAV now claims to follow semantic versioning
    - {{ pin_subpackage('av') }}

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config  # [not win]
    - msinttypes  # [win and py27]
  host:
    - python
    - pip
    - cython
    - numpy
    - ffmpeg
    - pillow
  run:
    - python
    - numpy
    - ffmpeg
    - pillow

test:
  imports:
    - av

about:
  home: https://github.com/mikeboers/PyAV/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Pythonic bindings for FFmpeg.'

  description: |
    PyAV is a Pythonic binding for FFmpeg or Libav. We aim to provide all of
    the power and control of the underlying library, but manage the gritty
    details as much as possible.
  doc_url: http://mikeboers.github.io/PyAV/
  dev_url: https://github.com/mikeboers/PyAV/

extra:
  recipe-maintainers:
    - danielballan
    - caspervdw
    - mikeboers
    - sdvillal
