{% set version = "10.0.0" %}

package:
  name: av
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/av/av-{{ version }}.tar.gz
  sha256: 8afd3d5610e1086f3b2d8389d66672ea78624516912c93612de64dcaa4c67e05

build:
  number: 6
  # Avoid solver dragging in cython 0.29.36 for py38 and avoid py3.13 for now
  skip: true  # [py<310 or py>=313]
  script: "{{ PYTHON }} -m pip install . --no-deps --no-cache-dir --no-build-isolation -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config  # [not win]
    # cross-compile helpers when build != target
    - python  # [build_platform != target_platform]
    - numpy   # [build_platform != target_platform]
    - cython >=0.29.36,<3
  host:
    - python >=3.10,<3.13
    - pip
    - numpy
    - ffmpeg
    - pillow
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pillow

test:
  imports:
    - av
  commands:
    - python -c "import av, importlib.metadata as im; print('av __version__:', getattr(av, '__version__', 'unknown')); print('pkg version:', im.version('av'))"

about:
  home: https://github.com/PyAV-Org/PyAV
  license: BSD-3-Clause
  license_family: BSD
  summary: Pythonic bindings for FFmpeg/Libav (PyAV)
  doc_url: https://pyav.org/docs/develop/
  dev_url: https://github.com/PyAV-Org/PyAV

extra:
  skip-lints:
    - host_section_needs_exact_pinnings
    - avoid_noarch
  recipe-maintainers:
    - ianaobi
    - danielballan
    - mikeboers
    - sdvillal
    - h-vetinari
    - hmaarrfk

