travis:
  secure:
    BINSTAR_TOKEN: WNKbQmN5mvdaL9gFwXKCEyfumAZ0Hh4H127Sd7hmLgtc8f23Dsb+u6NUEmWPSweFbsLU2cpcVJJpxk5CTcYTGZSkyCrRge5806foR26dPeGvPsBUsOAT9AqNNXz3Aj64TicH8Nc0d2NlZBf44wkpdy9JFKZqTLyvg6kVW7V2h96p7moF03K4NygRknIwgVIauQXHhwS+XKUZSY/2x8eaJnQ6lv3Hmnxah2xdTAkr3V04Qa7gdfqtZqvbZM9s44RzAN5PdFz7B680M2ae4BD6bPAmtZ8phKaVRHZjOK6dWLUm+qKfIpAOsPaUzVUC0Fy7lb7Qu2B3jXc66LXmaV0kQo0i30fVb0IIlp075bsy/EY9QeZk72Z0TWvOshvDpabcR2JdrfUfAZF4XFdMfMBTfdhqGcUmsTge2fVXF+5sm+sT3AlQIBEXEK3UxKcpBZyuXNQoWQttpxnYuoTO+Vz/fVwib3Du9z8kqApZRKTZ++uT1bLzfAJlmp9C3aXDaaXnDdLMtxsnnTumR/rzX/KDT7Kud4PRXzanSR5ZmW65eGlY9vPWE8+hzaXBLVZtn7WvpHz2qWIl6dzfdxSNoE3c+bw7Wp9qIWRq+wSzNgryrygIYysvH4WA4RXrq9glZHHdtyxzLugLOCsNZNGM8tQENybbOuC0cz2fe7HJWcRb+Dc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
