travis:
  secure:
    BINSTAR_TOKEN: EYZm1qDcu/lrIo692jrUiSAo3Ssj1VY7/en9VSNFVUK6oE5/8ZZNPE05gRpfCpgwsfrgGPo4YCmQRwwoOQgLc4nMVuK/Y0v4+Om8owItTs9rXymYM9CU0dvoolH8N75p+9diQnL3sMuqrt8VD4DMsfE+ff3XDlfheP9qQwXOVq8A7w0gtZ7PyELKCCQtqqrNdJp7XxbXGc0iHxmwI6riz5J3tZr1XFKX/nxXeZnkIYOL4HaMjDeWFsBRtT99UupTVOCfOox7x9OTTWmXRaI3qFqg44VDZhi1n66M9CZ6I/9cgKiq3KEdKulOQp7/xjDGxgKJaJPlHfDtlM1n2LU50McYGBelwNzMwrGYX7q6mSRS9BiXO57qheo9vXYxQTU2uP8jexPkSWdRVwBI4XLBONqTpwgMp2TpCz0NlT1vuAggoME2kJjDDYQSiN94JbqLCS7FNzFwX+Kvyo4WUIudnmlPzNLy7xI3C3QOnL4NCsu2SGltqmA3IBgZ00C0xYVjknPH0QqdWBIICzgLfxdBe4bZG5Eg7iqZ/jFYQ0xg3pRn9K8V21wQl9K7j4zTHWSIjH1gk/ea5RKTIn15ofVc2wILJYLaTl4tXkfnlU+BIQ57ZCOuqFKpln0iies9aI1dgXxAw2Kg2vZ92m5fDxe1sAM+kG6wxtZG9VfjWCFmHks=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
